class DemoPatientEntry {
  final String name;
  final String phone;
  final String email;
  final int age;
  final String gender;
  final int clinicIndex; // 0: City Care, 1: Apex Health, 2: Online
  final int archetypeIndex;
  final String area;
  final String address;
  final String occupation;
  final String maritalStatus;
  final String referralSource;
  final int registrationYear;
  final int registrationMonth;
  final int registrationDay;
  final int followUpCount; // 0 to 4 followups

  const DemoPatientEntry({
    required this.name,
    required this.phone,
    required this.email,
    required this.age,
    required this.gender,
    required this.clinicIndex,
    required this.archetypeIndex,
    required this.area,
    required this.address,
    required this.occupation,
    required this.maritalStatus,
    required this.referralSource,
    required this.registrationYear,
    required this.registrationMonth,
    required this.registrationDay,
    required this.followUpCount,
  });
}

class DemoPatientRoster {
  static const List<DemoPatientEntry> entries = [
    // ══════════════════════════════════════════════════════════════════
    // DECEMBER 2025 (9 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Tariq Mahmood',
      phone: '9830112233',
      email: 'tariq.mahmood@gmail.com',
      age: 52,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Central Avenue',
      address: '14/2 Park Street',
      occupation: 'Accountant',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 3,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Nusrat Jahan',
      phone: '9830223344',
      email: 'nusrat.jahan@yahoo.com',
      age: 36,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Salt Lake',
      address: 'Sector 1, Block B',
      occupation: 'School Teacher',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 5,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Rashid Khan',
      phone: '9830556677',
      email: 'rashid.khan@gmail.com',
      age: 60,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 5,
      area: 'Park Circus',
      address: '7 Palm Avenue',
      occupation: 'Retired Banker',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 8,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Ayaan Ali',
      phone: '9830334455',
      email: 'parent.ayaan@gmail.com',
      age: 8,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 1,
      area: 'Park Circus',
      address: '12 Orient Row',
      occupation: 'Student',
      maritalStatus: 'Single',
      referralSource: 'Dr. Sourav Sen',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 4,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Farhana Begum',
      phone: '9830445566',
      email: 'farhana.b@gmail.com',
      age: 29,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Ballygunge',
      address: '45 Rowland Road',
      occupation: 'HR Executive',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 9,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Dr. Sunita Sen',
      phone: '9830667788',
      email: 'sunita.sen@cu.ac.in',
      age: 49,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 4,
      area: 'New Alipore',
      address: 'Block C, Flat 4B',
      occupation: 'University Professor',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 13,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Amitabh Sen',
      phone: '9830114477',
      email: 'amitabh.sen@tcs.com',
      age: 34,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 6,
      area: 'Bengaluru (Remote)',
      address: 'Whitefield Tech Enclave',
      occupation: 'Senior Tech Lead',
      maritalStatus: 'Married',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 6,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Priyanka Roy',
      phone: '9830225588',
      email: 'priyanka.roy@gmail.com',
      age: 27,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 7,
      area: 'Hyderabad (Remote)',
      address: 'Gachibowli Cyber Towers',
      occupation: 'UI/UX Designer',
      maritalStatus: 'Single',
      referralSource: 'Online Website',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 11,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Rohit Sharma',
      phone: '9830336699',
      email: 'rohit.sharma@deloitte.com',
      age: 38,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 13,
      area: 'Mumbai (Remote)',
      address: 'Powai Lake Heights',
      occupation: 'Financial Analyst',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2025,
      registrationMonth: 12,
      registrationDay: 16,
      followUpCount: 3,
    ),

    // ══════════════════════════════════════════════════════════════════
    // JANUARY 2026 (11 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Zubair Ahmed',
      phone: '9830990011',
      email: 'zubair.ahmed@outlook.com',
      age: 22,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Bowbazar',
      address: '31 BB Ganguly Street',
      occupation: 'Software Engineer',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 2,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Arif Hossain',
      phone: '9831556677',
      email: 'arif.hossain@gmail.com',
      age: 44,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Chitpur',
      address: '55 Rabindra Sarani',
      occupation: 'Textile Merchant',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 5,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Wasim Akram',
      phone: '9831990011',
      email: 'wasim.akram@gmail.com',
      age: 38,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'Tiretti Bazaar',
      address: '18 Sun Yat Sen Street',
      occupation: 'Wholesale Trader',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 9,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Shahid Iqbal',
      phone: '9831112233',
      email: '',
      age: 48,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 9,
      area: 'Moulali',
      address: '22 AJC Bose Road',
      occupation: 'Store Manager',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 19,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Rehana Parveen',
      phone: '9831223344',
      email: 'rehana.parveen@gmail.com',
      age: 34,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 2,
      area: 'Sealdah',
      address: '9 Beliaghata Road',
      occupation: 'Homemaker',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 23,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Yasmin Akhtar',
      phone: '9830889900',
      email: 'yasmin.akhtar@yahoo.com',
      age: 41,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 4,
      area: 'Gariahat',
      address: '108 Rashbehari Avenue',
      occupation: 'Professor',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 6,
      followUpCount: 4,
    ),
    DemoPatientEntry(
      name: 'Tanveer Alam',
      phone: '9831334455',
      email: 'tanveer.alam@gmail.com',
      age: 32,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 8,
      area: 'Alipore',
      address: '17 Judges Court Road',
      occupation: 'Architect',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 13,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Suhail Mirza',
      phone: '9831778899',
      email: 'suhail.mirza@gmail.com',
      age: 55,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 0,
      area: 'Bhowanipore',
      address: '62 Harish Mukherjee Road',
      occupation: 'Civil Contractor',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 17,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Sabina Khatoon',
      phone: '9831889900',
      email: '',
      age: 46,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 14,
      area: 'Hazra',
      address: '33 SP Mukherjee Road',
      occupation: 'Homemaker',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 20,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Deepak Chawla',
      phone: '9830447700',
      email: 'deepak.c@amazon.com',
      age: 31,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 6,
      area: 'Delhi NCR (Remote)',
      address: 'Gurugram Sector 54',
      occupation: 'Operations Manager',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 10,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Ananya Mukherjee',
      phone: '9830558811',
      email: 'ananya.m@wipro.com',
      age: 26,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 3,
      area: 'Pune (Remote)',
      address: 'Hinjawadi Phase 2',
      occupation: 'Software Engineer',
      maritalStatus: 'Single',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 1,
      registrationDay: 22,
      followUpCount: 3,
    ),

    // ══════════════════════════════════════════════════════════════════
    // FEBRUARY 2026 (12 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Manish Agarwal',
      phone: '9830111001',
      email: 'manish.ag@gmail.com',
      age: 47,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 6,
      area: 'Burrabazar',
      address: '10 Cotton Street',
      occupation: 'Hardware Merchant',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 2,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Sangeeta Banerjee',
      phone: '9830111002',
      email: 'sangeeta.b@yahoo.com',
      age: 53,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Girish Park',
      address: '4 Vivekananda Road',
      occupation: 'School Principal',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 4,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Imran Qureshi',
      phone: '9830111003',
      email: 'imran.q@gmail.com',
      age: 39,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'Entally',
      address: '19 Convent Road',
      occupation: 'Footwear Manufacturer',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 9,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Debashis Roy',
      phone: '9830111004',
      email: 'debashis.roy@gmail.com',
      age: 62,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 5,
      area: 'Shyambazar',
      address: '88 Bidhan Sarani',
      occupation: 'Retired Government Officer',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 13,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Rupali Ghosh',
      phone: '9830111005',
      email: 'rupali.ghosh@outlook.com',
      age: 28,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Maniktala',
      address: '23 APC Road',
      occupation: 'Bank Officer',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 18,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Aditi Sengupta',
      phone: '9830111006',
      email: 'aditi.s@gmail.com',
      age: 35,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 2,
      area: 'Jodhpur Park',
      address: 'Flat 3B, Jodhpur Gardens',
      occupation: 'Content Strategist',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 3,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Vikramjit Das',
      phone: '9830111007',
      email: 'vikram.das@tata.com',
      age: 42,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 9,
      area: 'Tollygunge',
      address: '14 Golf Green Urban Complex',
      occupation: 'Supply Chain Manager',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 7,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Meenakshi Iyer',
      phone: '9830111008',
      email: 'meenakshi.i@gmail.com',
      age: 31,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Southern Avenue',
      address: '28 Keyatala Road',
      occupation: 'Chartered Accountant',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 12,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Pranab Chatterjee',
      phone: '9830111009',
      email: '',
      age: 58,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 14,
      area: 'Lake Gardens',
      address: '52 Prince Anwar Shah Road',
      occupation: 'Businessman',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 17,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Kavita Menon',
      phone: '9830111010',
      email: 'kavita.m@gmail.com',
      age: 33,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 7,
      area: 'Kochi (Remote)',
      address: 'Kakkanad Infopark Road',
      occupation: 'Tech Consultant',
      maritalStatus: 'Married',
      referralSource: 'Online Website',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 5,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Rohan Deshmukh',
      phone: '9830111011',
      email: 'rohan.d@gmail.com',
      age: 29,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 12,
      area: 'Nagpur (Remote)',
      address: 'Civil Lines Enclave',
      occupation: 'Civil Engineer',
      maritalStatus: 'Single',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 14,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Sneha Kulkarni',
      phone: '9830111012',
      email: 'sneha.k@gmail.com',
      age: 37,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 4,
      area: 'Indore (Remote)',
      address: 'Vijay Nagar Square',
      occupation: 'Fashion Designer',
      maritalStatus: 'Married',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 2,
      registrationDay: 21,
      followUpCount: 2,
    ),

    // ══════════════════════════════════════════════════════════════════
    // MARCH 2026 (13 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Subhashish Roy',
      phone: '9830111013',
      email: 'subhashish.roy@gmail.com',
      age: 50,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'College Street',
      address: '15 Surya Sen Street',
      occupation: 'Book Publisher',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 2,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Farzana Mallick',
      phone: '9830111014',
      email: 'farzana.m@gmail.com',
      age: 24,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Park Circus',
      address: '8 Dilkhusha Street',
      occupation: 'Research Scholar',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 4,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Kallol Bhattacharya',
      phone: '9830111015',
      email: 'kallol.b@gmail.com',
      age: 41,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 8,
      area: 'Beadon Street',
      address: '32 Beadon Row',
      occupation: 'Lawyer',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 9,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Mousumi Paul',
      phone: '9830111016',
      email: 'mousumi.p@yahoo.com',
      age: 38,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 2,
      area: 'Bagbazar',
      address: '12 Bosepara Lane',
      occupation: 'Teacher',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 13,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Gourab Dutta',
      phone: '9830111017',
      email: 'gourab.dutta@gmail.com',
      age: 30,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 13,
      area: 'Ultadanga',
      address: 'Block A, VIP Road',
      occupation: 'Corporate Lawyer',
      maritalStatus: 'Single',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 18,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Anindita Bose',
      phone: '9830111018',
      email: 'anindita.bose@gmail.com',
      age: 45,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 4,
      area: 'Kankurgachi',
      address: 'P-12 CIT Road',
      occupation: 'Homemaker',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 23,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Devendra Singhal',
      phone: '9830111019',
      email: 'devendra.s@gmail.com',
      age: 56,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 5,
      area: 'Ballygunge Circular',
      address: '18 Ballygunge Park',
      occupation: 'Industrialist',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 3,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Pooja Jhunjhunwala',
      phone: '9830111020',
      email: 'pooja.j@gmail.com',
      age: 28,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Lansdowne',
      address: '42 Sarat Bose Road',
      occupation: 'Jewelry Designer',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 10,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Samir Halder',
      phone: '9830111021',
      email: '',
      age: 63,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 9,
      area: 'Kasba',
      address: '77 Bosepukur Road',
      occupation: 'Retired Rail Engineer',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 14,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Nandini Mitra',
      phone: '9830111022',
      email: 'nandini.mitra@gmail.com',
      age: 36,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 7,
      area: 'Chetla',
      address: '24 Gobinda Auddy Road',
      occupation: 'Graphic Designer',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 21,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Arjun Kapoor',
      phone: '9830111023',
      email: 'arjun.k@flipkart.com',
      age: 32,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 6,
      area: 'Bengaluru (Remote)',
      address: 'Koramangala 4th Block',
      occupation: 'Product Manager',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 7,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Tanvi Saxena',
      phone: '9830111024',
      email: 'tanvi.saxena@gmail.com',
      age: 25,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 11,
      area: 'Jaipur (Remote)',
      address: 'C-Scheme Road',
      occupation: 'Architect',
      maritalStatus: 'Single',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 15,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Karan Mehra',
      phone: '9830111025',
      email: 'karan.mehra@gmail.com',
      age: 43,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 14,
      area: 'Chandigarh (Remote)',
      address: 'Sector 9 Enclave',
      occupation: 'Hotelier',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 3,
      registrationDay: 24,
      followUpCount: 2,
    ),

    // ══════════════════════════════════════════════════════════════════
    // APRIL 2026 (15 Patients - Spring Health Camp Month)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Bikramjit Mondal',
      phone: '9830111026',
      email: 'bikram.m@gmail.com',
      age: 54,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Hatibagan',
      address: '102 Bidhan Sarani',
      occupation: 'Timber Merchant',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 1,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Soma Ganguly',
      phone: '9830111027',
      email: 'soma.g@gmail.com',
      age: 39,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Sovabazar',
      address: '14 Raja Nabakrishna Street',
      occupation: 'Music Teacher',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 3,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Md. Firoz Alam',
      phone: '9830111028',
      email: 'firoz.alam@gmail.com',
      age: 46,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'Rajabazar',
      address: '76 Narkeldanga Main Road',
      occupation: 'Auto Garage Owner',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 8,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Jharna Nandi',
      phone: '9830111029',
      email: '',
      age: 65,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 5,
      area: 'Girish Park',
      address: '22 Ramdulal Sarkar Street',
      occupation: 'Homemaker',
      maritalStatus: 'Widowed',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 13,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Abhirup Guha',
      phone: '9830111030',
      email: 'abhirup.guha@gmail.com',
      age: 27,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Nimtala',
      address: '5 Strand Bank Road',
      occupation: 'Junior Doctor',
      maritalStatus: 'Single',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 17,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Kakali Majumdar',
      phone: '9830111031',
      email: 'kakali.m@gmail.com',
      age: 42,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 4,
      area: 'Beleghata',
      address: '89 CIT Scheme',
      occupation: 'Primary Teacher',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 20,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Avishek Poddar',
      phone: '9830111032',
      email: 'avishek.poddar@gmail.com',
      age: 33,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 8,
      area: 'Bowbazar',
      address: '47 Ganesh Chandra Avenue',
      occupation: 'Goldsmith',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 24,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Madhulika Somani',
      phone: '9830111033',
      email: 'madhulika.s@gmail.com',
      age: 26,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Elgin Road',
      address: '15 Ashutosh Mukherjee Road',
      occupation: 'Investment Banker',
      maritalStatus: 'Single',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 2,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Rajnish Kothari',
      phone: '9830111034',
      email: 'rajnish.k@gmail.com',
      age: 51,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 6,
      area: 'Minto Park',
      address: '4 DL Khan Road',
      occupation: 'Share Broker',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 7,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Sharmila Tagore Roy',
      phone: '9830111035',
      email: 'sharmila.tr@gmail.com',
      age: 48,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 2,
      area: 'Ballygunge Place',
      address: '31/1 Dover Lane',
      occupation: 'Vocal Artist',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 11,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Nirmalendu Sarkar',
      phone: '9830111036',
      email: '',
      age: 67,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 0,
      area: 'Dhakuria',
      address: '11 Gariahat Road South',
      occupation: 'Retired Professor',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 14,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Payal Khaitan',
      phone: '9830111037',
      email: 'payal.k@gmail.com',
      age: 30,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 7,
      area: 'Triangular Park',
      address: '67 Purna Das Road',
      occupation: 'Boutique Owner',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 18,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Debopriya Roy',
      phone: '9830111038',
      email: 'debopriya.r@gmail.com',
      age: 29,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 3,
      area: 'Chennai (Remote)',
      address: 'OMR Tech Corridor',
      occupation: 'Data Scientist',
      maritalStatus: 'Single',
      referralSource: 'Online Website',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 6,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Manish Pandey',
      phone: '9830111039',
      email: 'manish.p@gmail.com',
      age: 40,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 13,
      area: 'Lucknow (Remote)',
      address: 'Gomti Nagar Extension',
      occupation: 'State Tax Officer',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 16,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Rashmi Verma',
      phone: '9830111040',
      email: 'rashmi.v@gmail.com',
      age: 35,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 2,
      area: 'Ahmedabad (Remote)',
      address: 'Bodakdev Enclave',
      occupation: 'University Faculty',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 4,
      registrationDay: 22,
      followUpCount: 2,
    ),

    // ══════════════════════════════════════════════════════════════════
    // MAY 2026 (16 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Swapan Kumar Paul',
      phone: '9830111041',
      email: 'swapan.paul@gmail.com',
      age: 59,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 9,
      area: 'Kumartuli',
      address: '8 Banamali Sarkar Street',
      occupation: 'Sculptor Artist',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 1,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Sabnam Parveen',
      phone: '9830111042',
      email: 'sabnam.p@gmail.com',
      age: 32,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Sealdah',
      address: '14 Canal East Road',
      occupation: 'Nursing Staff',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 4,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Pratap Chandra Seal',
      phone: '9830111043',
      email: 'pratap.seal@gmail.com',
      age: 48,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 6,
      area: 'Ahiritola',
      address: '29 Ahiritola Street',
      occupation: 'Hardware Trader',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 8,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Ruma Mukherjee',
      phone: '9830111044',
      email: 'ruma.m@gmail.com',
      age: 44,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Bagbazar',
      address: '56 Girish Avenue',
      occupation: 'Librarian',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 13,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Sheikh Nasiruddin',
      phone: '9830111045',
      email: 'nasir.sheikh@gmail.com',
      age: 52,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 14,
      area: 'Tiretti Bazaar',
      address: '12 Phears Lane',
      occupation: 'Shoe Exporter',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 18,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Poulomi Dasgupta',
      phone: '9830111046',
      email: 'poulomi.dg@gmail.com',
      age: 23,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Shyambazar',
      address: '11 Bhupen Bose Avenue',
      occupation: 'College Student',
      maritalStatus: 'Single',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 22,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Kamal Kishore Rathi',
      phone: '9830111047',
      email: 'kamal.rathi@gmail.com',
      age: 55,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'Burrabazar',
      address: '8 Raja Woodmunt Street',
      occupation: 'Textile Agent',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 27,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Anupam Bagchi',
      phone: '9830111048',
      email: 'anupam.b@gmail.com',
      age: 41,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 8,
      area: 'Bhowanipore',
      address: '4 Padmapukur Road',
      occupation: 'Senior Advocate',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 2,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Lipika Goswami',
      phone: '9830111049',
      email: 'lipika.g@gmail.com',
      age: 37,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 4,
      area: 'Kalighat',
      address: '19 Nakuleshwar Bhattacharjee Lane',
      occupation: 'School Teacher',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 7,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Vivek Singhania',
      phone: '9830111050',
      email: 'vivek.s@gmail.com',
      age: 46,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 5,
      area: 'Alipore Park',
      address: '9 Alipore Avenue',
      occupation: 'Financial Consultant',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 12,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Chandana Chakraborty',
      phone: '9830111051',
      email: 'chandana.c@gmail.com',
      age: 51,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 0,
      area: 'Lake Market',
      address: '14 Janak Road',
      occupation: 'Homemaker',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 16,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Tanushree Bhattacharya',
      phone: '9830111052',
      email: 'tanushree.b@gmail.com',
      age: 28,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Gariahat',
      address: '78 Ekdalia Road',
      occupation: 'Fashion Stylist',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 21,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Harsh Vardhan Agarwal',
      phone: '9830111053',
      email: 'harsh.va@gmail.com',
      age: 36,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 6,
      area: 'Park Street',
      address: '55 Mother Teresa Sarani',
      occupation: 'Restaurateur',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 26,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Vipin Narang',
      phone: '9830111054',
      email: 'vipin.n@gmail.com',
      age: 41,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 9,
      area: 'Noida (Remote)',
      address: 'Sector 62 IT Park',
      occupation: 'Software VP',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 5,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Geetanjali Rao',
      phone: '9830111055',
      email: 'geetanjali.r@gmail.com',
      age: 30,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 7,
      area: 'Goa (Remote)',
      address: 'Panaji Heritage Quarter',
      occupation: 'Yoga Instructor',
      maritalStatus: 'Single',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 15,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Abhinav Tyagi',
      phone: '9830111056',
      email: 'abhinav.tyagi@gmail.com',
      age: 33,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 13,
      area: 'Gurugram (Remote)',
      address: 'DLF Cyber City Phase 3',
      occupation: 'Management Consultant',
      maritalStatus: 'Married',
      referralSource: 'Online Website',
      registrationYear: 2026,
      registrationMonth: 5,
      registrationDay: 25,
      followUpCount: 2,
    ),

    // ══════════════════════════════════════════════════════════════════
    // JUNE 2026 (17 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Pradip Sengupta',
      phone: '9830111057',
      email: 'pradip.sengupta@gmail.com',
      age: 61,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'College Street',
      address: '44 Harrison Road',
      occupation: 'Stationery Supplier',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 1,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Nasreen Bano',
      phone: '9830111058',
      email: 'nasreen.b@gmail.com',
      age: 35,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 2,
      area: 'Park Circus',
      address: '19 European Asylum Lane',
      occupation: 'Embroidery Specialist',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 3,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Biswanath Karmakar',
      phone: '9830111059',
      email: '',
      age: 50,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 8,
      area: 'Sealdah',
      address: '11 Surya Sen Street',
      occupation: 'Jewelry Artisan',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 8,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Madhumita Roy',
      phone: '9830111060',
      email: 'madhumita.roy@gmail.com',
      age: 41,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 4,
      area: 'Maniktala',
      address: '33 Raja Dinendra Street',
      occupation: 'High School Teacher',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 12,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Ashok Kumar Shaw',
      phone: '9830111061',
      email: 'ashok.shaw@gmail.com',
      age: 54,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 14,
      area: 'Chitpur',
      address: '77 Rabindra Sarani',
      occupation: 'Sweet Shop Owner',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 17,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Deblina Ghosh',
      phone: '9830111062',
      email: 'deblina.ghosh@gmail.com',
      age: 25,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Bowbazar',
      address: '8 Bow Street',
      occupation: 'Interior Designer',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 22,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Md. Shahidul Islam',
      phone: '9830111063',
      email: 'shahidul.islam@gmail.com',
      age: 43,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Moulali',
      address: '5 SN Banerjee Road',
      occupation: 'Leather Merchant',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 26,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Rajendra Prasad Gupta',
      phone: '9830111064',
      email: 'rajendra.pg@gmail.com',
      age: 64,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 5,
      area: 'Rowland Road',
      address: '14 Rowland Enclave',
      occupation: 'Retired Tea Planter',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 2,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Indrani Bose',
      phone: '9830111065',
      email: 'indrani.b@gmail.com',
      age: 31,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Ballygunge Circular',
      address: '37 Ballygunge Circular Road',
      occupation: 'Architect',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 6,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Soumen Mukherjee',
      phone: '9830111066',
      email: 'soumen.m@gmail.com',
      age: 49,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 9,
      area: 'Tollygunge',
      address: '109 NSC Bose Road',
      occupation: 'Film Editor',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 11,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Anupama Dalmia',
      phone: '9830111067',
      email: 'anupama.d@gmail.com',
      age: 38,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 2,
      area: 'Alipore',
      address: '22 Belvedere Road',
      occupation: 'Art Curator',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 16,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Debabrata Sen',
      phone: '9830111068',
      email: '',
      age: 58,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 6,
      area: 'New Alipore',
      address: 'Block G, Flat 2A',
      occupation: 'Structural Consultant',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 20,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Mallika Sarabhai Roy',
      phone: '9830111069',
      email: 'mallika.sr@gmail.com',
      age: 45,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 0,
      area: 'Southern Avenue',
      address: '52 Lake Avenue',
      occupation: 'Classical Singer',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 25,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Raghav Singhal',
      phone: '9830111070',
      email: 'raghav.s@gmail.com',
      age: 34,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 6,
      area: 'Dubai UAE (Remote)',
      address: 'Downtown Dubai Boulevard',
      occupation: 'Investment Director',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 4,
      followUpCount: 3,
    ),
    DemoPatientEntry(
      name: 'Divya Nambiar',
      phone: '9830111071',
      email: 'divya.nambiar@gmail.com',
      age: 28,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 7,
      area: 'London UK (Remote)',
      address: 'Canary Wharf High Street',
      occupation: 'Fintech Specialist',
      maritalStatus: 'Single',
      referralSource: 'Online Website',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 14,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Aditya Mathur',
      phone: '9830111072',
      email: 'aditya.m@gmail.com',
      age: 37,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 12,
      area: 'Jaipur (Remote)',
      address: 'Vaishali Nagar Enclave',
      occupation: 'Automobile Dealer',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 19,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Kritika Sharma',
      phone: '9830111073',
      email: 'kritika.s@gmail.com',
      age: 27,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 11,
      area: 'Mumbai (Remote)',
      address: 'Bandra West Hill Road',
      occupation: 'Brand Strategist',
      maritalStatus: 'Single',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 6,
      registrationDay: 28,
      followUpCount: 1,
    ),

    // ══════════════════════════════════════════════════════════════════
    // JULY 2026 (18 Patients - Senior Wellness Camp Month)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Dhirendra Nath Bose',
      phone: '9830111074',
      email: '',
      age: 71,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Hatibagan',
      address: '18 Raja Dinendra Street',
      occupation: 'Retired School Headmaster',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 1,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Sultana Begum',
      phone: '9830111075',
      email: 'sultana.b@gmail.com',
      age: 47,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 14,
      area: 'Rajabazar',
      address: '39 Gas Street',
      occupation: 'Homemaker',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 3,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Subir Kumar Mitra',
      phone: '9830111076',
      email: 'subir.mitra@gmail.com',
      age: 53,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 6,
      area: 'Bowbazar',
      address: '61 Nirmal Chandra Street',
      occupation: 'Hardware Merchant',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 8,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Shabana Azmi Sheikh',
      phone: '9830111077',
      email: 'shabana.s@gmail.com',
      age: 38,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Park Circus',
      address: '14 Beckbagan Row',
      occupation: 'Tailoring Teacher',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 13,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Satyajit Ray Chaudhury',
      phone: '9830111078',
      email: 'satyajit.rc@gmail.com',
      age: 49,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'College Square',
      address: '8 Bankim Chatterjee Street',
      occupation: 'Bookseller',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 17,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Aparna Sen Majumdar',
      phone: '9830111079',
      email: 'aparna.sm@gmail.com',
      age: 40,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 4,
      area: 'Sealdah',
      address: '22 Chatu Babu Lane',
      occupation: 'Govt Clerk',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 22,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Nripendra Narayan Das',
      phone: '9830111080',
      email: '',
      age: 68,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 5,
      area: 'Shyambazar',
      address: '105 Raja Dinendra Street',
      occupation: 'Retired Postal Clerk',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 27,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Bhaskar Jyoti Roy',
      phone: '9830111081',
      email: 'bhaskar.jr@gmail.com',
      age: 52,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 9,
      area: 'Bhowanipore',
      address: '28 Kansaripara Road',
      occupation: 'Bank Manager',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 2,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Rupanjana Mitra',
      phone: '9830111082',
      email: 'rupanjana.m@gmail.com',
      age: 33,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Ballygunge Place',
      address: '11 Ballygunge Terrace',
      occupation: 'HR Consultant',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 7,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Gopal Krishna Jalan',
      phone: '9830111083',
      email: 'gopal.jalan@gmail.com',
      age: 57,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 8,
      area: 'Park Street',
      address: '14 Park Mansions',
      occupation: 'Stock Broker',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 11,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Mahua Banerjee',
      phone: '9830111084',
      email: 'mahua.b@gmail.com',
      age: 46,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 2,
      area: 'Alipore',
      address: '8 Alipore Heights',
      occupation: 'College Lecturer',
      maritalStatus: 'Married',
      referralSource: 'Dr. K. N. Sen Memorial',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 16,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Shankar Lal Murarka',
      phone: '9830111085',
      email: '',
      age: 69,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 0,
      area: 'Hazra',
      address: '42 Beltala Road',
      occupation: 'Retired Businessman',
      maritalStatus: 'Married',
      referralSource: 'Free Health Camp',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 21,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Priyadarshini Sen',
      phone: '9830111086',
      email: 'priyadarshini.s@gmail.com',
      age: 26,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 11,
      area: 'Southern Avenue',
      address: '92 Hemanta Mukherjee Sarani',
      occupation: 'Software Engineer',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 25,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Himanshu Agarwal',
      phone: '9830111087',
      email: 'himanshu.ag@gmail.com',
      age: 39,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 6,
      area: 'Minto Park',
      address: '11 Pretoria Street',
      occupation: 'Real Estate Developer',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 28,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Abhishek Kulkarni',
      phone: '9830111088',
      email: 'abhishek.k@gmail.com',
      age: 36,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 13,
      area: 'Singapore (Remote)',
      address: 'Marina Bay Financial Center',
      occupation: 'Fintech Director',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 5,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Sushmita Pillai',
      phone: '9830111089',
      email: 'sushmita.pillai@gmail.com',
      age: 32,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 4,
      area: 'Thiruvananthapuram (Remote)',
      address: 'Kowdiar Palace Enclave',
      occupation: 'Civil Judge',
      maritalStatus: 'Married',
      referralSource: 'Online Website',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 12,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Gaurav Bhatnagar',
      phone: '9830111090',
      email: 'gaurav.b@gmail.com',
      age: 42,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 12,
      area: 'Dehradun (Remote)',
      address: 'Rajpur Road Estate',
      occupation: 'Botanical Researcher',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 18,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Sonali Chakraborty',
      phone: '9830111091',
      email: 'sonali.c@gmail.com',
      age: 29,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 7,
      area: 'Bhubaneswar (Remote)',
      address: 'Chandrasekharpur Housing Board',
      occupation: 'Architect',
      maritalStatus: 'Single',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 7,
      registrationDay: 26,
      followUpCount: 1,
    ),

    // ══════════════════════════════════════════════════════════════════
    // AUGUST 2026 (10 Patients)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Tarun Kumar Bose',
      phone: '9830111092',
      email: 'tarun.bose@gmail.com',
      age: 56,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Bagbazar',
      address: '19 Kanto Pukur Lane',
      occupation: 'Hardware Trader',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 3,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Zeenat Aman Khan',
      phone: '9830111093',
      email: 'zeenat.ak@gmail.com',
      age: 33,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Park Circus',
      address: '42 Kimber Street',
      occupation: 'School Teacher',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 7,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Alok Nath Gangopadhyay',
      phone: '9830111094',
      email: 'alok.nath@gmail.com',
      age: 62,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 5,
      area: 'Sovabazar',
      address: '11 Raja Debendra Street',
      occupation: 'Retired Land Surveyor',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 12,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Priyanka Das',
      phone: '9830111095',
      email: 'priyanka.das@gmail.com',
      age: 24,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 11,
      area: 'Maniktala',
      address: '6 Canal West Road',
      occupation: 'M.Tech Student',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 17,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Kashif Mehmood',
      phone: '9830111096',
      email: 'kashif.m@gmail.com',
      age: 41,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 10,
      area: 'Tiretti Bazaar',
      address: '22 Damzen Lane',
      occupation: 'Leather Exporter',
      maritalStatus: 'Married',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 24,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Aniruddha Lahiri',
      phone: '9830111097',
      email: 'aniruddha.l@gmail.com',
      age: 47,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 8,
      area: 'Alipore',
      address: '19 National Library Avenue',
      occupation: 'Senior Corporate Lawyer',
      maritalStatus: 'Married',
      referralSource: 'Suraksha Diagnostics',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 4,
      followUpCount: 2,
    ),
    DemoPatientEntry(
      name: 'Monideepa Roy',
      phone: '9830111098',
      email: 'monideepa.r@gmail.com',
      age: 30,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 3,
      area: 'Ballygunge Park',
      address: '7 Queen\'s Park Road',
      occupation: 'Investment Analyst',
      maritalStatus: 'Married',
      referralSource: 'FitZone Gym',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 11,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Debjit Sengupta',
      phone: '9830111099',
      email: 'debjit.s@gmail.com',
      age: 53,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 9,
      area: 'Jodhpur Park',
      address: '92 Jodhpur Park Block A',
      occupation: 'Architectural Consultant',
      maritalStatus: 'Married',
      referralSource: 'ActiveLife Physio',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 18,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Pooja Agarwal',
      phone: '9830111100',
      email: 'pooja.agarwal@gmail.com',
      age: 36,
      gender: 'Female',
      clinicIndex: 1,
      archetypeIndex: 2,
      area: 'Minto Park',
      address: '14 Wood Street',
      occupation: 'Fashion Merchant',
      maritalStatus: 'Married',
      referralSource: 'DentCare Oral Health',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 25,
      followUpCount: 1,
    ),
    DemoPatientEntry(
      name: 'Siddharth Varma',
      phone: '9830111101',
      email: 'siddharth.v@gmail.com',
      age: 38,
      gender: 'Male',
      clinicIndex: 2,
      archetypeIndex: 6,
      area: 'Sydney Australia (Remote)',
      address: 'Parramatta CBD Towers',
      occupation: 'Solutions Architect',
      maritalStatus: 'Married',
      referralSource: 'Existing Patient',
      registrationYear: 2026,
      registrationMonth: 8,
      registrationDay: 10,
      followUpCount: 1,
    ),

    // ══════════════════════════════════════════════════════════════════
    // SEPTEMBER 2026 (4 Patients - Month to Date)
    // ══════════════════════════════════════════════════════════════════
    DemoPatientEntry(
      name: 'Nirmalya Banerjee',
      phone: '9830111102',
      email: 'nirmalya.b@gmail.com',
      age: 49,
      gender: 'Male',
      clinicIndex: 0,
      archetypeIndex: 0,
      area: 'Central Avenue',
      address: '28 Chittaranjan Avenue',
      occupation: 'Chartered Accountant',
      maritalStatus: 'Married',
      referralSource: 'MediPlus Pharmacy',
      registrationYear: 2026,
      registrationMonth: 9,
      registrationDay: 1,
      followUpCount: 0,
    ),
    DemoPatientEntry(
      name: 'Samira Hashmi',
      phone: '9830111103',
      email: 'samira.h@gmail.com',
      age: 27,
      gender: 'Female',
      clinicIndex: 0,
      archetypeIndex: 1,
      area: 'Park Circus',
      address: '15 Circus Avenue',
      occupation: 'High School Teacher',
      maritalStatus: 'Single',
      referralSource: 'Word of mouth',
      registrationYear: 2026,
      registrationMonth: 9,
      registrationDay: 1,
      followUpCount: 0,
    ),
    DemoPatientEntry(
      name: 'Prateek Somani',
      phone: '9830111104',
      email: 'prateek.somani@gmail.com',
      age: 35,
      gender: 'Male',
      clinicIndex: 1,
      archetypeIndex: 6,
      area: 'Park Street',
      address: '77 Park Street 1st Floor',
      occupation: 'Commercial Banker',
      maritalStatus: 'Married',
      referralSource: 'Google Maps / Search',
      registrationYear: 2026,
      registrationMonth: 9,
      registrationDay: 1,
      followUpCount: 0,
    ),
    DemoPatientEntry(
      name: 'Neha Radhakrishnan',
      phone: '9830111105',
      email: 'neha.rk@gmail.com',
      age: 31,
      gender: 'Female',
      clinicIndex: 2,
      archetypeIndex: 3,
      area: 'Bengaluru (Remote)',
      address: 'Indiranagar 100 Feet Road',
      occupation: 'Lead Product Designer',
      maritalStatus: 'Married',
      referralSource: 'Instagram / Social Media',
      registrationYear: 2026,
      registrationMonth: 9,
      registrationDay: 2,
      followUpCount: 0,
    ),
  ];
}
